name: Statsio
values:
  - key: base_url
    value: 'http://localhost:8080'
    enabled: true
  - key: email
    value: corentin.gesse@gmail.com
    enabled: true
  - key: password
    value: password
    enabled: true
  - key: language
    value: fr
    enabled: true
  - key: token
    value: ''
    enabled: true
  - key: token_type
    value: Bearer
    enabled: true
  - key: refresh_token
    value: ''
    enabled: true
  - key: channel_id
    value: ''
    enabled: true
  - key: user_id
    value: ''
    enabled: true
  - key: google_id_token
    value: ''
    enabled: true
  - key: statsdata_document_id
    value: ''
    enabled: true
  - key: statsdata_source_id
    value: ''
    enabled: true
