name: Deploy Laravel to LWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          set -e

          mkdir -p ~/.ssh

          # clé privée
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          # known_hosts (évite les prompts interactifs)
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          set -e

          ssh -i ~/.ssh/id_ed25519 \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'

            set -e

            cd ~/public_html/statsio/statsio-api

            echo "📥 Pull code"
            git pull origin main

            echo "📦 Composer install"
            composer install --no-dev --optimize-autoloader

            echo "🧱 Laravel optimize"
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            echo "✅ Deploy OK"
          EOF